{
 "title": "Meldungen Kanton ZH",
 "time": { "from": "2024-07-31T22:00:00.000Z", "to": "2024-08-31T22:00:00.000Z" },
 "panels": [
  {
   "title": "Meldungen Kanton ZH Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"officialgazette\")\r\n  |> range(start: 2024-08-01, stop: 2024-08-31)\r\n  |> filter(fn: (r) => r._measurement == \"publication\")\r\n  |> filter(fn: (r) => r.cantons == \"\\\"ZH\\\"\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: 1d, fn: count, createEmpty: true)\r\n  |> yield(name: \"count\")"
    }
   ]
  },
  {
   "title": "Meldungen Kanton ZH pro Sub-Rubrik",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"officialgazette\")\r\n  |> range(start: 2024-08-01, stop: 2024-08-31)\r\n  |> range(start: -366d)\r\n  |> filter(fn: (r) => r._measurement == \"publication\")\r\n  |> filter(fn: (r) => r.cantons == \"\\\"ZH\\\"\")\r\n  |> group(columns: [\"subRubric\"])\r\n  |> aggregateWindow(every: 1d, fn: count)\r\n  |> yield(name: \"subRubric count per day\")"
    }
   ]
  },
  {
   "title": "Meldungen Kanton ZH pro Sub-Rubrik für 08.2024",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"officialgazette\")\r\n  |> range(start: 2024-08-01, stop: 2024-08-31)\r\n  |> filter(fn: (r) => r._measurement == \"publication\")\r\n  |> filter(fn: (r) => r.cantons == \"\\\"ZH\\\"\")\r\n  |> group(columns: [\"subRubric\"])\r\n  |> aggregateWindow(every: 1d, fn: count)\r\n  |> yield(name: \"subRubric count per day\")"
    }
   ]
  },
  {
   "title": "Meldungen Kanton ZH pro Sub-Rubrik",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"officialgazette\")\r\n  |> range(start: 2024-08-01, stop: 2024-08-31)\r\n  |> filter(fn: (r) => r._measurement == \"publication\")\r\n  |> filter(fn: (r) => r.cantons == \"\\\"ZH\\\"\")\r\n  |> group(columns: [\"subRubric\"])\r\n  |> aggregateWindow(every: 1d, fn: count)\r\n  |> yield(name: \"subRubric count per day\")"
    }
   ]
  },
  {
   "title": "Meldungen pro Erfasser und Sub-Rubrik",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"officialgazette\")\r\n  |> range(start: 2024-08-01, stop: 2024-08-31)\r\n  |> filter(fn: (r) => r._measurement == \"publication\")\r\n  |> filter(fn: (r) => r.cantons == \"\\\"ZH\\\"\")\r\n  |> map(fn: (r) => ({\r\n      r with \r\n      displayName: strings.replaceAll(v: r.displayName, t: \"\\\"\", u: \"\"),  // Remove double quotes\r\n      subRubric: strings.replaceAll(v: r.subRubric, t: \"\\\"\", u: \"\")  // Remove double quotes\r\n  }))\r\n  |> map(fn: (r) => ({\r\n      r with \r\n      combinedLabel: r.displayName + \" - \" + r.subRubric\r\n  }))\r\n  |> keep(columns: [\"combinedLabel\", \"_time\", \"_value\"]) \r\n  |> group(columns: [\"combinedLabel\"])\r\n  |> aggregateWindow(every: 1d, fn: count, createEmpty: false)\r\n  |> yield(name: \"subRubric count per day\")"
    }
   ]
  },
  {
   "title": "Meldungen vom Eidg. Amt für das Handelsregister",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"officialgazette\")\r\n  |> range(start: 2024-08-01, stop: 2024-08-31)\r\n  |> filter(fn: (r) => r._measurement == \"publication\")\r\n  |> filter(fn: (r) => r.cantons == \"\\\"ZH\\\"\")\r\n  |> filter(fn: (r) => strings.containsStr(v: r.displayName, substr: \"das Handelsregister\"))\r\n  |> keep(columns: [\"subRubric\", \"_time\", \"_value\"]) \r\n  |> group(columns: [\"subRubric\"])\r\n  |> aggregateWindow(every: 1d, fn: count, createEmpty: true) "
    }
   ]
  }
 ]
}