{
 "title": "Meldungen Kanton ZH",
 "time": { "from": "2024-06-23T22:00:00.000Z", "to": "2024-07-09T22:00:00.000Z" },
 "panels": [
  {
   "title": "Meldungen Kanton ZH Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"officialgazette\")\r\n  |> range(start: 2024-06-24, stop: 2024-07-10)\r\n  |> filter(fn: (r) => r._measurement == \"publication\")\r\n  |> filter(fn: (r) => r.cantons == \"\\\"ZH\\\"\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: 1d, fn: count, createEmpty: true)\r\n  |> yield(name: \"count\")"
    }
   ]
  },
  {
   "title": "Meldungen Kanton ZH pro subRubric",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"officialgazette\")\r\n  // |> range(start: 2024-06-24, stop: 2024-07-10)\r\n  |> range(start: -366d)\r\n  |> filter(fn: (r) => r._measurement == \"publication\")\r\n  |> filter(fn: (r) => r.cantons == \"\\\"ZH\\\"\")\r\n  |> group(columns: [\"subRubric\"])\r\n  |> aggregateWindow(every: 1d, fn: count)\r\n  |> yield(name: \"subRubric count per day\")"
    }
   ]
  },
  {
   "title": "Meldungen Kanton ZH pro subRubric für 01.07.2024",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"officialgazette\")\r\n  |> range(start: 2024-07-01, stop: 2024-07-02)\r\n  |> filter(fn: (r) => r._measurement == \"publication\")\r\n  |> filter(fn: (r) => r.cantons == \"\\\"ZH\\\"\")\r\n  |> group(columns: [\"subRubric\"])\r\n  |> aggregateWindow(every: 1d, fn: count)\r\n  |> yield(name: \"subRubric count per day\")"
    }
   ]
  },
  {
   "title": "Meldungen Kanton ZH pro subRubric",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"officialgazette\")\r\n  |> range(start: 2024-06-24, stop: 2024-07-10)\r\n  |> filter(fn: (r) => r._measurement == \"publication\")\r\n  |> filter(fn: (r) => r.cantons == \"\\\"ZH\\\"\")\r\n  |> group(columns: [\"subRubric\"])\r\n  |> aggregateWindow(every: 1d, fn: count)\r\n  |> yield(name: \"subRubric count per day\")"
    }
   ]
  },
  {
   "title": "Meldungen pro Erfasser",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"officialgazette\")\r\n  |> range(start: 2024-06-24, stop: 2024-07-10)\r\n  |> filter(fn: (r) => r._measurement == \"publication\")\r\n  |> filter(fn: (r) => r.cantons == \"\\\"ZH\\\"\")\r\n  |> group(columns: [\"displayName\"])  // Group by displayName\r\n  |> keep(columns: [\"displayName\", \"_time\", \"_value\"]) \r\n  |> aggregateWindow(every: v.windowPeriod, fn: count)  "
    }
   ]
  },
  {
   "title": "Meldungen vom Handelsregisteramt ZH",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"officialgazette\")\r\n  |> range(start: 2024-06-24, stop: 2024-07-10)\r\n  |> filter(fn: (r) => r._measurement == \"publication\")\r\n  |> filter(fn: (r) => r.cantons == \"\\\"ZH\\\"\")\r\n  |> filter(fn: (r) => strings.containsStr(v: r.displayName, substr: \"Handelsregisteramt\"))\r\n  |> keep(columns: [\"displayName\", \"_time\", \"value\", \"_value\"]) \r\n  |> aggregateWindow(every: 1d, fn: count, createEmpty: true)  "
    }
   ]
  }
 ]
}